name: "EK Shellcheck"
description: "Action for checking scripts with shellcheck"
author: "ESSENTIALKAOS"

branding:
  icon: 'hash'
  color: 'yellow'

inputs:
  files:
    description: "Scripts for checking"
    required: true

  version:
    description: "Version of shellcheck"
    required: false
    default: "0.7.2"

  severity:
    description: "Minimum severity of errors to consider"
    required: false
    default: "style"

runs:
  using: "composite"
  steps:
    - id: shellcheck-install
      name: Install Shellcheck 
      shell: bash
      run: |
        echo "::group::Downloading Shellcheck…"
        sc_url="https://github.com/koalaman/shellcheck/releases/download"

        if [[ "$RUNNER_OS" == "Linux" ]] ; then
          wget -q -O shellcheck.tar.xz ${sc_url}/v${{inputs.version}}/shellcheck-v${{inputs.version}}.linux.x86_64.tar.xz
        elif [[ "$RUNNER_OS" == "macOS" ]] ; then
          wget -q -O shellcheck.tar.xz ${sc_url}/v${{inputs.version}}/shellcheck-v${{inputs.version}}.darwin.x86_64.tar.xz
        else
          echo "$RUNNER_OS is not supported"
          exit 1  
        fi

        echo "::endgroup::"
        echo "::group::Unpacking Shellcheck…"

        tar xf shellcheck.tar.xz -C "$GITHUB_ACTION_PATH"

        mv "$GITHUB_ACTION_PATH/shellcheck-v${{inputs.version}}/shellcheck" \
           "$GITHUB_ACTION_PATH"

        echo "::endgroup::"

    - id: shellcheck-version-print
      name: Print Shellcheck version info
      shell: bash
      run: |
        echo "::group::Shellcheck version info"
        $GITHUB_ACTION_PATH/shellcheck --version
        echo "::endgroup::"

    - id: shellcheck-check
      name: Checks scripts with Shellcheck
      shell: bash
      run: |
        echo "Running shellcheck…"
        bash -c 'shopt -s globstar; $GITHUB_ACTION_PATH/shellcheck --severity=${{inputs.severity}} ${{inputs.files}}' && echo "Everything is OK!"
